# Generated by Django 4.1.7 on 2023-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_grade',
            field=models.FloatField(default=1.0),
        ),
    ]
